import {
  createSummary,
  setTotalRows,
  incrementConformesExplicitosReales,
  incrementTotalNoFindingAntes,
  registerDiscardedByEmptyHallazgo,
  registerDiscardedEmptyRow,
  registerAutoGeneratedConforme,
  registerFinalRecordInSummary,
  buildSuccessPayload
} from './excel/analyzeExcel/summary.js';
import {
  detectHeaders as detectExcelHeaders,
  loadExcelParsingContext,
  createFillDownState
} from './excel/analyzeExcel/excel-io.js';
import { processRow } from './excel/analyzeExcel/recordProcessor.js';
import { OPERATIVE_AREAS } from './excel/analyzeExcel/public.js';
import { normalizeCellValue, normalizeIncidentText } from './analyzeExcel/normalizers.js';

const ENABLE_CLASSIFICATION_TRACE = process.env.CLASSIFICATION_TRACE === '1';
const ENABLE_FILLDOWN_TRACE = process.env.EXCEL_FILLDOWN_TRACE === '1';

function hasUsefulDeviationText(text = '') {
  const normalized = normalizeIncidentText(text || '');
  if (!normalized) return false;
  return !['-', 'na', 'n a', 'nd', 'n d', 's d', 's/d'].includes(normalized);
}

/**
 * Analiza un archivo Excel y clasifica desvios en base a reglas textuales objetivas.
 */
export async function analyzeExcel(fileBuffer, _businessRules, progressCallback = null) {
  const enableDebugDiagnostics = process.env.DEBUG_EXCEL_ANALYSIS === 'true';
  const results = [];

  const summary = createSummary();

  try {
    progressCallback?.(10, 'Validando archivo...');

    const {
      headerRowIndex,
      headerValues,
      rows,
      headerIndexes,
      diagnostics: parsingDiagnostics
    } = await loadExcelParsingContext(fileBuffer);

    progressCallback?.(30, 'Leyendo datos del Excel...');

    const totalRows = rows.length;
    setTotalRows(summary, totalRows);

    const contextState = {
      negativeLeadWindow: 0,
      leadTopicText: '',
      maxLeadWindow: 3
    };
    const fillDownState = createFillDownState();
    const diagnostics = {
      hasFile: true,
      workbookSheets: parsingDiagnostics?.workbookSheets || [],
      worksheetSelected: parsingDiagnostics?.worksheetSelected || null,
      worksheetRanking: parsingDiagnostics?.worksheetRanking || [],
      totalPhysicalRows: totalRows,
      detectedHeaderRow: parsingDiagnostics?.detectedHeaderRow ?? headerRowIndex,
      detectedHeaders: parsingDiagnostics?.detectedHeaders || headerIndexes,
      deviationColumnIndex: parsingDiagnostics?.deviationColumnIndex ?? null,
      rowsWithDeviationText: 0,
      discardedRowsCount: 0,
      discardedSamples: [],
      rowsAudit: [],
      recordsAfterProcessing: 0,
      recordsSentToFrontend: 0
    };

    rows.forEach((rowValues, index) => {
      progressCallback?.(
        40 + Math.floor((index / totalRows) * 40),
        `Clasificando registro ${index + 1} de ${totalRows}...`
      );

      const processed = processRow({
        index,
        rowValues,
        headerRowIndex,
        headerValues,
        headerIndexes,
        fillDownState,
        contextState,
        enableClassificationTrace: ENABLE_CLASSIFICATION_TRACE,
        enableFillDownTrace: ENABLE_FILLDOWN_TRACE
      });

      const rawDeviationValue = normalizeCellValue(
        Number.isInteger(diagnostics.deviationColumnIndex)
          ? rowValues?.[diagnostics.deviationColumnIndex]
          : ''
      ).trim();
      const normalizedDeviationValue = normalizeIncidentText(rawDeviationValue);
      if (enableDebugDiagnostics && diagnostics.rowsAudit.length < 2000) {
        diagnostics.rowsAudit.push({
          rowNumber: headerRowIndex + index + 1,
          rawDeviationValue,
          normalizedDeviationValue,
          accepted: !processed.skipped,
          discardReason: processed.skipped ? (processed.discardedReason || 'unknown') : null
        });
      }

      if (hasUsefulDeviationText(rawDeviationValue)) {
        diagnostics.rowsWithDeviationText += 1;
      }

      if (processed.skipped) {
        diagnostics.discardedRowsCount += 1;
        if (diagnostics.discardedSamples.length < 20) {
          diagnostics.discardedSamples.push({
            rowNumber: headerRowIndex + index + 1,
            reason: processed.discardedReason || 'unknown',
            rawDeviationValue: processed.discardedByEmptyHallazgoPayload?.desvioDetectado || '-',
            normalizedDeviationValue: processed.discardedByEmptyHallazgoPayload?.desvioDetectado || '-'
          });
        }
      }

      if (processed.incrementConformesExplicitosReales) {
        incrementConformesExplicitosReales(summary);
      }
      if (processed.incrementNoFindingAntes) {
        incrementTotalNoFindingAntes(summary);
      }

      if (processed.discardedByEmptyHallazgoPayload) {
        registerDiscardedByEmptyHallazgo(summary, processed.discardedByEmptyHallazgoPayload);
      }
      if (processed.discardedEmptyRowPayload) {
        registerDiscardedEmptyRow(summary, processed.discardedEmptyRowPayload);
      }

      if (processed.skipped) {
        return;
      }

      if (processed.isAutoConforme && !processed.explicitRawNoFinding) {
        registerAutoGeneratedConforme(summary, processed.finalRecord, processed.rawRecord);
        return;
      }

      registerFinalRecordInSummary(summary, processed.finalRecord);

      results.push(processed.finalRecord);
    });

    const successPayload = buildSuccessPayload(results, summary);
    diagnostics.recordsAfterProcessing = results.length;
    diagnostics.recordsSentToFrontend = successPayload.records.length;
    if (enableDebugDiagnostics) {
      successPayload.diagnostics = diagnostics;
    }

    return successPayload;
  } catch (error) {
    progressCallback?.(0, `Error: ${error.message}`);
    return {
      success: false,
      error: error.message,
      records: [],
      summary: null
    };
  }
}

/**
 * Detecta encabezados del Excel con aliases para gestion diaria y reunion de desvios.
 */
export function detectHeaders(headerRow) {
  return detectExcelHeaders(headerRow);
}

export { OPERATIVE_AREAS };
