import {
  createSummary,
  setTotalRows,
  incrementConformesExplicitosReales,
  incrementTotalNoFindingAntes,
  registerDiscardedByEmptyHallazgo,
  registerDiscardedEmptyRow,
  registerAutoGeneratedConforme,
  registerFinalRecordInSummary,
  buildSuccessPayload
} from './excel/analyzeExcel/summary.js';
import {
  detectHeaders as detectExcelHeaders,
  loadExcelParsingContext,
  createFillDownState
} from './excel/analyzeExcel/excel-io.js';
import { processRow } from './excel/analyzeExcel/recordProcessor.js';
import { OPERATIVE_AREAS } from './excel/analyzeExcel/public.js';
import { normalizeCellValue, normalizeIncidentText } from './analyzeExcel/normalizers.js';

const ENABLE_CLASSIFICATION_TRACE = process.env.CLASSIFICATION_TRACE === '1';
const ENABLE_FILLDOWN_TRACE = process.env.EXCEL_FILLDOWN_TRACE === '1';

function hasUsefulDeviationText(text = '') {
  const normalized = normalizeIncidentText(text || '');
  if (!normalized) return false;
  return !['-', 'na', 'n a', 'nd', 'n d', 's d', 's/d'].includes(normalized);
}

function extractYearCandidates(raw = '') {
  const text = normalizeCellValue(raw).trim();
  if (!text) return [];
  const years = [];
  const iso = text.match(/\b(20\d{2})[-/]\d{1,2}[-/]\d{1,2}\b/);
  if (iso) years.push(Number(iso[1]));
  const dmy = text.match(/\b\d{1,2}[-/]\d{1,2}[-/](20\d{2})\b/);
  if (dmy) years.push(Number(dmy[1]));
  return years.filter((y) => y >= 2000 && y <= 2100);
}

function pickMostFrequentYear(years = []) {
  const counts = new Map();
  years.forEach((year) => {
    if (!Number.isInteger(year)) return;
    counts.set(year, (counts.get(year) || 0) + 1);
  });
  if (!counts.size) return null;
  return [...counts.entries()].sort((a, b) => b[1] - a[1])[0][0];
}

function extractYearFromFilename(filename = '') {
  const match = String(filename || '').match(/\b(20\d{2})\b/);
  if (!match) return null;
  const y = Number(match[1]);
  return Number.isInteger(y) ? y : null;
}

function inferYearFromMonthNameWithoutYear(filename = '', now = new Date()) {
  const text = normalizeIncidentText(filename || '');
  if (!text) return null;
  const monthMap = new Map([
    ['enero', 1], ['febrero', 2], ['marzo', 3], ['abril', 4], ['mayo', 5], ['junio', 6],
    ['julio', 7], ['agosto', 8], ['septiembre', 9], ['setiembre', 9], ['octubre', 10], ['noviembre', 11], ['diciembre', 12]
  ]);
  let detectedMonth = null;
  for (const [name, month] of monthMap.entries()) {
    if (text.includes(name)) {
      detectedMonth = month;
      break;
    }
  }
  if (!detectedMonth) return null;
  const currentYear = now.getFullYear();
  const currentMonth = now.getMonth() + 1;
  return detectedMonth > currentMonth ? currentYear - 1 : currentYear;
}

/**
 * Analiza un archivo Excel y clasifica desvios en base a reglas textuales objetivas.
 */
export async function analyzeExcel(fileBuffer, _businessRules, progressCallback = null, options = {}) {
  const enableDebugDiagnostics = process.env.DEBUG_EXCEL_ANALYSIS === 'true';
  const results = [];

  const summary = createSummary();

  try {
    progressCallback?.(10, 'Validando archivo...');

    const {
      headerRowIndex,
      headerValues,
      rows,
      headerIndexes,
      diagnostics: parsingDiagnostics
    } = await loadExcelParsingContext(fileBuffer);

    progressCallback?.(30, 'Leyendo datos del Excel...');

    const totalRows = rows.length;
    setTotalRows(summary, totalRows);

    const contextState = {
      negativeLeadWindow: 0,
      leadTopicText: '',
      maxLeadWindow: 3
    };
    const fillDownState = createFillDownState();
    const explicitYearsFound = [];
    const yearCounts = new Map();
    if (Number.isInteger(headerIndexes.fecha)) {
      rows.forEach((row) => {
        const candidates = extractYearCandidates(row?.[headerIndexes.fecha]);
        candidates.forEach((y) => {
          explicitYearsFound.push(y);
          yearCounts.set(y, (yearCounts.get(y) || 0) + 1);
        });
      });
    }
    const metadataYears = [];
    const workbookMeta = parsingDiagnostics?.workbookMeta || {};
    extractYearCandidates(workbookMeta.created || '').forEach((y) => metadataYears.push(y));
    extractYearCandidates(workbookMeta.modified || '').forEach((y) => metadataYears.push(y));
    (parsingDiagnostics?.workbookSheets || []).forEach((sheetInfo) => {
      extractYearCandidates(sheetInfo?.name || '').forEach((y) => metadataYears.push(y));
    });

    const fileNameYear = extractYearFromFilename(options?.filename || '');
    const inferredYearFromFileMonth = fileNameYear
      ? fileNameYear
      : inferYearFromMonthNameWithoutYear(options?.filename || '', options?.uploadedAt ? new Date(options.uploadedAt) : new Date());
    let usedCurrentYearFallback = false;
    if (yearCounts.size > 0) {
      fillDownState.contextYear = pickMostFrequentYear(explicitYearsFound);
    }
    if (!Number.isInteger(fillDownState.contextYear) && Number.isInteger(options?.analysisYear)) {
      fillDownState.contextYear = options.analysisYear;
    }
    if (!Number.isInteger(fillDownState.contextYear) && Number.isInteger(fileNameYear)) {
      fillDownState.contextYear = fileNameYear;
    }
    if (!Number.isInteger(fillDownState.contextYear) && Number.isInteger(inferredYearFromFileMonth)) {
      fillDownState.contextYear = inferredYearFromFileMonth;
    }
    if (!Number.isInteger(fillDownState.contextYear)) {
      fillDownState.contextYear = pickMostFrequentYear(metadataYears);
    }
    const currentYear = new Date().getFullYear();
    if (
      Number.isInteger(inferredYearFromFileMonth)
      && Number.isInteger(fillDownState.contextYear)
      && fillDownState.contextYear === currentYear
      && yearCounts.size > 0
    ) {
      fillDownState.contextYear = inferredYearFromFileMonth;
    }
    if (!Number.isInteger(fillDownState.contextYear)) {
      fillDownState.contextYear = currentYear;
      usedCurrentYearFallback = true;
    }
    const diagnostics = {
      hasFile: true,
      workbookSheets: parsingDiagnostics?.workbookSheets || [],
      worksheetSelected: parsingDiagnostics?.worksheetSelected || null,
      worksheetRanking: parsingDiagnostics?.worksheetRanking || [],
      totalPhysicalRows: totalRows,
      detectedHeaderRow: parsingDiagnostics?.detectedHeaderRow ?? headerRowIndex,
      detectedHeaders: parsingDiagnostics?.detectedHeaders || headerIndexes,
      deviationColumnIndex: parsingDiagnostics?.deviationColumnIndex ?? null,
      rowsWithDeviationText: 0,
      discardedRowsCount: 0,
      discardedSamples: [],
      rowsAudit: [],
      recordsAfterProcessing: 0,
      recordsSentToFrontend: 0,
      dateParsing: {
        inferredContextYear: fillDownState.contextYear,
        explicitYearsFound: [...new Set(explicitYearsFound)],
        dateColumnIndex: Number.isInteger(headerIndexes.fecha) ? headerIndexes.fecha : null,
        sampleRawDates: Number.isInteger(headerIndexes.fecha)
          ? rows
            .slice(0, 20)
            .map((row) => normalizeCellValue(row?.[headerIndexes.fecha]).trim())
            .filter(Boolean)
          : [],
        sampleParsedDates: [],
        usedCurrentYearFallback,
        filenameYear: fileNameYear,
        inferredYearFromFileMonth,
        rows: [],
        warning: null
      }
    };

    rows.forEach((rowValues, index) => {
      progressCallback?.(
        40 + Math.floor((index / totalRows) * 40),
        `Clasificando registro ${index + 1} de ${totalRows}...`
      );

      const processed = processRow({
        index,
        rowValues,
        headerRowIndex,
        headerValues,
        headerIndexes,
        fillDownState,
        contextState,
        enableClassificationTrace: ENABLE_CLASSIFICATION_TRACE,
        enableFillDownTrace: ENABLE_FILLDOWN_TRACE
      });

      const rawDeviationValue = normalizeCellValue(
        Number.isInteger(diagnostics.deviationColumnIndex)
          ? rowValues?.[diagnostics.deviationColumnIndex]
          : ''
      ).trim();
      const normalizedDeviationValue = normalizeIncidentText(rawDeviationValue);
      if (enableDebugDiagnostics && diagnostics.rowsAudit.length < 2000) {
        diagnostics.rowsAudit.push({
          rowNumber: headerRowIndex + index + 1,
          rawDeviationValue,
          normalizedDeviationValue,
          accepted: !processed.skipped,
          discardReason: processed.skipped ? (processed.discardedReason || 'unknown') : null
        });
      }

      if (hasUsefulDeviationText(rawDeviationValue)) {
        diagnostics.rowsWithDeviationText += 1;
      }

      if (processed.skipped) {
        diagnostics.discardedRowsCount += 1;
        if (diagnostics.discardedSamples.length < 20) {
          diagnostics.discardedSamples.push({
            rowNumber: headerRowIndex + index + 1,
            reason: processed.discardedReason || 'unknown',
            rawDeviationValue: processed.discardedByEmptyHallazgoPayload?.desvioDetectado || '-',
            normalizedDeviationValue: processed.discardedByEmptyHallazgoPayload?.desvioDetectado || '-'
          });
        }
      }

      if (processed.incrementConformesExplicitosReales) {
        incrementConformesExplicitosReales(summary);
      }
      if (processed.incrementNoFindingAntes) {
        incrementTotalNoFindingAntes(summary);
      }

      if (processed.discardedByEmptyHallazgoPayload) {
        registerDiscardedByEmptyHallazgo(summary, processed.discardedByEmptyHallazgoPayload);
      }
      if (processed.discardedEmptyRowPayload) {
        registerDiscardedEmptyRow(summary, processed.discardedEmptyRowPayload);
      }

      if (processed.skipped) {
        return;
      }

      if (diagnostics.dateParsing.sampleParsedDates.length < 20) {
        diagnostics.dateParsing.sampleParsedDates.push({
          rowNumber: headerRowIndex + index + 1,
          parsedDate: normalizeCellValue(processed.finalRecord?.fecha).trim()
        });
      }
      if (enableDebugDiagnostics && processed.dateDebug && diagnostics.dateParsing.rows.length < 1000) {
        diagnostics.dateParsing.rows.push({
          ...processed.dateDebug,
          usedCurrentYearFallback: usedCurrentYearFallback && processed.dateDebug.contextYearUsed === currentYear
        });
      }

      if (processed.isAutoConforme && !processed.explicitRawNoFinding) {
        registerAutoGeneratedConforme(summary, processed.finalRecord, processed.rawRecord);
        return;
      }

      registerFinalRecordInSummary(summary, processed.finalRecord);

      results.push(processed.finalRecord);
    });

    const successPayload = buildSuccessPayload(results, summary);
    if (
      diagnostics.dateParsing.usedCurrentYearFallback
      && diagnostics.dateParsing.rows.length > 0
      && diagnostics.dateParsing.rows.every((row) => row.rawDateType === 'dmy_without_year' || row.rawDateType === 'empty')
    ) {
      diagnostics.dateParsing.warning = 'Fechas sin año explícito parseadas con fallbackYear';
    }
    diagnostics.recordsAfterProcessing = results.length;
    diagnostics.recordsSentToFrontend = successPayload.records.length;
    if (enableDebugDiagnostics) {
      successPayload.diagnostics = diagnostics;
    }

    return successPayload;
  } catch (error) {
    progressCallback?.(0, `Error: ${error.message}`);
    return {
      success: false,
      error: error.message,
      records: [],
      summary: null
    };
  }
}

/**
 * Detecta encabezados del Excel con aliases para gestion diaria y reunion de desvios.
 */
export function detectHeaders(headerRow) {
  return detectExcelHeaders(headerRow);
}

export { OPERATIVE_AREAS };
