import {
  createSummary,
  setTotalRows,
  incrementConformesExplicitosReales,
  incrementTotalNoFindingAntes,
  registerDiscardedByEmptyHallazgo,
  registerDiscardedEmptyRow,
  registerAutoGeneratedConforme,
  registerFinalRecordInSummary,
  buildSuccessPayload
} from './excel/analyzeExcel/summary.js';
import {
  detectHeaders as detectExcelHeaders,
  loadExcelParsingContext,
  createFillDownState
} from './excel/analyzeExcel/excel-io.js';
import { processRow } from './excel/analyzeExcel/recordProcessor.js';
import { OPERATIVE_AREAS } from './excel/analyzeExcel/public.js';

const ENABLE_CLASSIFICATION_TRACE = process.env.CLASSIFICATION_TRACE === '1';
const ENABLE_FILLDOWN_TRACE = process.env.EXCEL_FILLDOWN_TRACE === '1';

/**
 * Analiza un archivo Excel y clasifica desvios en base a reglas textuales objetivas.
 */
export async function analyzeExcel(fileBuffer, _businessRules, progressCallback = null) {
  const results = [];

  const summary = createSummary();

  try {
    progressCallback?.(10, 'Validando archivo...');

    const {
      headerRowIndex,
      headerValues,
      rows,
      headerIndexes
    } = await loadExcelParsingContext(fileBuffer);

    progressCallback?.(30, 'Leyendo datos del Excel...');

    const totalRows = rows.length;
    setTotalRows(summary, totalRows);

    const contextState = {
      negativeLeadWindow: 0,
      leadTopicText: '',
      maxLeadWindow: 3
    };
    const fillDownState = createFillDownState();

    rows.forEach((rowValues, index) => {
      progressCallback?.(
        40 + Math.floor((index / totalRows) * 40),
        `Clasificando registro ${index + 1} de ${totalRows}...`
      );

      const processed = processRow({
        index,
        rowValues,
        headerRowIndex,
        headerValues,
        headerIndexes,
        fillDownState,
        contextState,
        enableClassificationTrace: ENABLE_CLASSIFICATION_TRACE,
        enableFillDownTrace: ENABLE_FILLDOWN_TRACE
      });

      if (processed.incrementConformesExplicitosReales) {
        incrementConformesExplicitosReales(summary);
      }
      if (processed.incrementNoFindingAntes) {
        incrementTotalNoFindingAntes(summary);
      }

      if (processed.discardedByEmptyHallazgoPayload) {
        registerDiscardedByEmptyHallazgo(summary, processed.discardedByEmptyHallazgoPayload);
      }
      if (processed.discardedEmptyRowPayload) {
        registerDiscardedEmptyRow(summary, processed.discardedEmptyRowPayload);
      }

      if (processed.skipped) {
        return;
      }

      if (processed.isAutoConforme && !processed.explicitRawNoFinding) {
        registerAutoGeneratedConforme(summary, processed.finalRecord, processed.rawRecord);
        return;
      }

      registerFinalRecordInSummary(summary, processed.finalRecord);

      results.push(processed.finalRecord);
    });

    const successPayload = buildSuccessPayload(results, summary);

    return successPayload;
  } catch (error) {
    progressCallback?.(0, `Error: ${error.message}`);
    return {
      success: false,
      error: error.message,
      records: [],
      summary: null
    };
  }
}

/**
 * Detecta encabezados del Excel con aliases para gestion diaria y reunion de desvios.
 */
export function detectHeaders(headerRow) {
  return detectExcelHeaders(headerRow);
}

export { OPERATIVE_AREAS };
