import {
  normalizeCellValue,
  normalizeForMatch,
  containsAny,
  buildRowObjectFromExcel,
  buildNormalizedRowKeyMap,
  getRowValueByCandidates,
  normalizeIncidentText
} from '../../analyzeExcel/normalizers.js';
import {
  classifyAuditCompliance,
  hasExplicitNegativeSignal,
  detectCriticalNegativeSignal,
  isNeutralTechnicalMention,
  classifyTechnicalControlRule,
  classifyPriorityOperationalRule,
  hasRowContinuationSignal,
  isExplicitNoFindingText,
  isExplicitNoFindingRawValue,
  isAutoGeneratedConformeRecord,
  classifyNormalizedRule,
  classifyOutcomeFromRow,
  parseOriginalTipoDesvio
} from './classifiers/outcomeClassifier.js';
import {
  classifyIso22000FromDescription,
  mergeCompositeIsoLabels,
  resolveIsoWithContextFallback
} from './classifiers/isoClassifier.js';
import {
  classifyCategoriaDesvio,
  applyGovernanceTypeAndCategory
} from './classifiers/categoryClassifier.js';
import { classifyDeviationScope, normalizeScope } from './classifiers/scopeClassifier.js';
import {
  hasOperationalDeviationSignal,
  shouldUseAreaProcesoAsHallazgo,
  applyOperationalOverrides,
  detectAreasFromDescription,
  composeAreaClasificada,
  normalizeBrunoArea
} from './classifiers/areaClassifier.js';
import {
  esTextoAccion,
  getTextoAccion,
  buildActions,
  classifyResponsibleByArea,
  classifyActionStatusFromRow
} from './actions.js';
import { validateFinalRecord } from './validation.js';
import { detectCompanyAreaFromRecord } from './companyDetector.js';
import {
  splitHallazgos,
  isGestionSgiaText,
  isTextoNoValidoHallazgo,
  isInvalidDetectedFinding,
  hasUsefulFindingText,
  extractYearFromIsoDate,
  hasExplicitYearToken,
  parseFechaValue,
  inferRawDateType,
  isUsefulNonHallazgoValue,
  isGenericCategoryLabelAsArea,
  contieneArea,
  sanitizeHallazgo,
  isRepeatedHeaderRow,
  getHallazgo,
  getTextoHallazgo,
  buildClassificationText,
  buildClassificationExplanation,
  classifyConfidence,
  buildAnalysisText,
  normalizeClassificationForStats,
  normalizeScopeForStats,
  applyActionFallbacks,
  buildFinalRecordPayload,
  resolveScopeMetadata,
  applyOriginalClassificationOverride,
  applyInocuidadHardPriority
} from './recordProcessor.utils.js';

function processRow({
  index,
  rowValues,
  headerRowIndex,
  headerValues,
  headerIndexes,
  fillDownState,
  contextState,
  enableClassificationTrace,
  enableFillDownTrace
}) {
  const getValue = (headerIndex) => {
    const indexToUse = Number.isInteger(headerIndex) ? headerIndex : null;
    return indexToUse == null ? '' : rowValues?.[indexToUse];
  };
  const hasExplicitOriginalValue = (value = '') => {
    const normalized = normalizeForMatch(normalizeCellValue(value || '').trim());
    if (!normalized) return false;
    return ![
      '-',
      'na',
      'n a',
      'nd',
      'n d',
      's d',
      's/d',
      'no aplica',
      'sin dato',
      'sin datos',
      'pendiente',
      'revisar manualmente',
      'revision manual',
      'area',
      'area sector',
      'area proceso',
      'clasificacion',
      'clasificacion del desvio',
      'clasificación del desvío',
      'tipo',
      'estado',
      'responsable'
    ].includes(normalized);
  };

  const row = buildRowObjectFromExcel(headerValues, rowValues);
  const rowKeyMap = buildNormalizedRowKeyMap(row);
  const accionDetectada = getTextoAccion(row);

  const actividadRealizadaRaw = getRowValueByCandidates(row, rowKeyMap, [
    'Actividad realizada',
    'Actividad realizada / Descripción',
    'Actividad realizada / Descripcion'
  ]) || normalizeCellValue(getValue(headerIndexes.actividadRealizada));

  const tipoActividadRaw = getRowValueByCandidates(row, rowKeyMap, [
    'Tipo de actividad',
    'Tipo actividad'
  ]) || normalizeCellValue(getValue(headerIndexes.tipoActividad));

  const areaProcesoRaw = getRowValueByCandidates(row, rowKeyMap, [
    'Área / Proceso',
    'Area / Proceso',
    'Área / Sector',
    'Area / Sector',
    'Área/Proceso',
    'Area/Proceso',
    'Sector',
    'Area'
  ]) || normalizeCellValue(getValue(headerIndexes.areaProceso));

  const resultadoRaw = getRowValueByCandidates(row, rowKeyMap, [
    'Resultado'
  ]) || normalizeCellValue(getValue(headerIndexes.resultado));

  const desvioRaw = getRowValueByCandidates(row, rowKeyMap, [
    '¿Desvío?',
    '¿Desvio?',
    'Desvío',
    'Desvio'
  ]) || normalizeCellValue(getValue(headerIndexes.desvio));

  const accionRaw = getRowValueByCandidates(row, rowKeyMap, [
    '¿Acción?',
    '¿Accion?',
    'Acción',
    'Accion'
  ]) || normalizeCellValue(getValue(headerIndexes.accion));

  const numeroAccionRaw = getRowValueByCandidates(row, rowKeyMap, [
    'N° Acción',
    'N° Accion',
    'Nro Acción',
    'Nro Accion',
    'Numero accion'
  ]) || normalizeCellValue(getValue(headerIndexes.numeroAccion));

  const notaTecnicaRaw = getRowValueByCandidates(row, rowKeyMap, [
    'Nota técnica',
    'Nota tecnica'
  ]) || normalizeCellValue(getValue(headerIndexes.notaTecnica));

  const fechaRaw = normalizeCellValue(getRowValueByCandidates(row, rowKeyMap, [
    'Fecha',
    'Fecha del desvío',
    'Fecha del desvio',
    'Fecha de registro'
  ]) || getValue(headerIndexes.fecha)).trim();

  const responsableOriginalRaw = normalizeCellValue(getRowValueByCandidates(row, rowKeyMap, ['Responsable', 'Responsable asignado']) || '').trim();
  const iso22000OriginalRaw = normalizeCellValue(getRowValueByCandidates(row, rowKeyMap, [
    'ISO 22000',
    'Iso 22000',
    'ISO',
    'Clausula ISO',
    'Cláusula ISO'
  ]) || '').trim();
  const classificationOriginalRaw = normalizeCellValue(getRowValueByCandidates(row, rowKeyMap, [
    'Clasificacion del desvio',
    'Clasificación del desvío',
    'Clasificacion del desvío',
    'Clasificación del desvio',
    'Clasificación',
    'Clasificacion',
    'Categoría',
    'Categoria',
    'Categoría del desvío',
    'Categoria del desvio',
    'Resultado clasificado'
  ]) || '').trim();
  const tipoDesvioOriginalRaw = normalizeCellValue(getRowValueByCandidates(row, rowKeyMap, [
    'Tipo desvio',
    'Tipo desvío',
    'Tipo'
  ]) || '').trim();
  const scopeOriginalRaw = normalizeCellValue(getRowValueByCandidates(row, rowKeyMap, [
    'Desvío interno/externo',
    'Desvio interno/externo',
    'Desvío externo/ Interno',
    'Desvio externo/ Interno',
    'Desvío externo / Interno',
    'Desvio externo / Interno',
    'Desvio externo/interno'
  ]) || '').trim();

  const desvioDetectadoOriginal = normalizeCellValue(getRowValueByCandidates(row, rowKeyMap, [
    'Desvío detectado',
    'Desvio detectado',
    'Hallazgo detectado'
  ]) || getValue(headerIndexes.hallazgoDetectado) || '').trim();
  const areaOriginal = normalizeCellValue(areaProcesoRaw).trim();
  const descripcionRaw = getRowValueByCandidates(row, rowKeyMap, [
    'Descripción',
    'Descripcion',
    'Descripción del desvío',
    'Descripcion del desvio',
    'Detalle del desvío',
    'Detalle del desvio'
  ]) || normalizeCellValue(getValue(headerIndexes.descripcion));
  const observacionesRaw = getRowValueByCandidates(row, rowKeyMap, [
    'Observaciones',
    'Observación',
    'Observacion'
  ]) || normalizeCellValue(getValue(headerIndexes.observaciones));
  const accionInmediataRaw = getRowValueByCandidates(row, rowKeyMap, [
    'Acción inmediata',
    'Accion inmediata'
  ]) || normalizeCellValue(getValue(headerIndexes.accionInmediata));
  const accionCorrectivaRaw = getRowValueByCandidates(row, rowKeyMap, [
    'Acción Correctiva Propuesta',
    'Accion Correctiva Propuesta',
    'Acción correctiva propuesta',
    'Accion correctiva propuesta',
    'Acción correctiva',
    'Accion correctiva'
  ]) || normalizeCellValue(getValue(headerIndexes.accionCorrectiva));
  const estadoAccionRaw = normalizeCellValue(getRowValueByCandidates(row, rowKeyMap, [
    'Estado',
    'Estado acción',
    'Estado accion',
    'Status',
    'Estado de acción',
    'Estado de accion'
  ]) || '').trim();
  const hallazgoRawText = normalizeCellValue(desvioDetectadoOriginal).trim();
  const noFindingSignal = isExplicitNoFindingText(hallazgoRawText);
  const hallazgoVacioOInvalido = isInvalidDetectedFinding(hallazgoRawText);
  const hallazgoSanitizado = sanitizeHallazgo(hallazgoRawText);
  const becameNoFindingAfterSanitize = normalizeForMatch(hallazgoSanitizado) === normalizeForMatch('Sin hallazgo detectado') && !noFindingSignal;

  const hasSupportData = [
    fechaRaw,
    areaProcesoRaw,
    responsableOriginalRaw,
    descripcionRaw,
    observacionesRaw,
    accionRaw,
    accionInmediataRaw,
    accionCorrectivaRaw,
    notaTecnicaRaw,
    numeroAccionRaw
  ].some((value) => isUsefulNonHallazgoValue(value));
  const shouldDiscardByEmptyHallazgo = hallazgoVacioOInvalido || becameNoFindingAfterSanitize;
  const shouldDiscardAsEmptyRow = !noFindingSignal && !hasSupportData && hallazgoVacioOInvalido;

  const fechaParsed = parseFechaValue(fechaRaw, fillDownState.fecha, fillDownState.contextYear);
  let fecha = fechaParsed || fillDownState.fecha;
  const parsedYear = extractYearFromIsoDate(fecha);
  const hasExplicitYear = hasExplicitYearToken(fechaRaw);
  if (
    fecha
    && Number.isInteger(fillDownState.contextYear)
    && Number.isInteger(parsedYear)
    && !hasExplicitYear
    && parsedYear !== fillDownState.contextYear
  ) {
    const [, mm = '', dd = ''] = String(fecha).match(/^\d{4}-(\d{2})-(\d{2})$/) || [];
    if (mm && dd) {
      fecha = `${String(fillDownState.contextYear).padStart(4, '0')}-${mm}-${dd}`;
    }
  }
  const areaProcesoRawNormalized = normalizeCellValue(areaProcesoRaw).trim();
  const canInheritAreaFromFillDown = fillDownState.areaProceso && !isGenericCategoryLabelAsArea(fillDownState.areaProceso);
  const areaProceso = areaProcesoRawNormalized || (canInheritAreaFromFillDown ? fillDownState.areaProceso : '');
  const actividadRealizada = normalizeCellValue(actividadRealizadaRaw).trim() || fillDownState.actividadRealizada;
  const tipoActividad = normalizeCellValue(tipoActividadRaw).trim() || fillDownState.tipoActividad;
  const resultado = normalizeCellValue(resultadoRaw).trim();
  const desvio = normalizeCellValue(desvioRaw).trim();
  const accion = normalizeCellValue(accionRaw).trim();
  const numeroAccion = normalizeCellValue(numeroAccionRaw).trim();
  const notaTecnica = normalizeCellValue(notaTecnicaRaw).trim();
  const responsableOriginal = responsableOriginalRaw || fillDownState.responsableOriginal;
  const iso22000Original = iso22000OriginalRaw || fillDownState.iso22000Original;
  const classificationOriginal = classificationOriginalRaw || fillDownState.classificationOriginal;
  const tipoDesvioOriginal = tipoDesvioOriginalRaw || fillDownState.tipoDesvioOriginal;

  if (fecha && normalizeForMatch(fecha) !== 'fecha') {
    fillDownState.fecha = fecha;
    const y = extractYearFromIsoDate(fecha);
    if (Number.isInteger(y)) fillDownState.contextYear = y;
  }
  if (
    areaProcesoRawNormalized
    && !['area', 'area sector', 'area proceso'].includes(normalizeForMatch(areaProcesoRawNormalized))
    && !isGenericCategoryLabelAsArea(areaProcesoRawNormalized)
  ) {
    fillDownState.areaProceso = areaProcesoRawNormalized;
  }
  if (actividadRealizada && normalizeForMatch(actividadRealizada) !== 'actividad realizada') fillDownState.actividadRealizada = actividadRealizada;
  if (tipoActividad && normalizeForMatch(tipoActividad) !== 'tipo de actividad') fillDownState.tipoActividad = tipoActividad;
  if (responsableOriginal) fillDownState.responsableOriginal = responsableOriginal;
  if (iso22000Original) fillDownState.iso22000Original = iso22000Original;
  if (classificationOriginal) fillDownState.classificationOriginal = classificationOriginal;
  if (tipoDesvioOriginal) fillDownState.tipoDesvioOriginal = tipoDesvioOriginal;

  const hasRealRowSignal = hasUsefulFindingText(desvioDetectadoOriginal);
  const invalidDetectedFinding = !hasUsefulFindingText(desvioDetectadoOriginal);

  if (!hasRealRowSignal || invalidDetectedFinding || shouldDiscardAsEmptyRow || shouldDiscardByEmptyHallazgo) {
    const discardedReason = shouldDiscardByEmptyHallazgo
      ? (becameNoFindingAfterSanitize ? 'desvio_detectado_no_util_post_sanitize' : 'desvio_detectado_vacio')
      : (shouldDiscardAsEmptyRow
        ? 'fila_vacia_incompleta'
        : (!hasRealRowSignal ? 'sin_senales_reales' : 'desvio_detectado_invalido'));
    if (enableFillDownTrace) {
      console.log('[fill-down-discarded]', {
        index: index + 1,
        motivo: discardedReason,
        desvioDetectadoOriginal,
        areaOriginal,
        tipoDesvioOriginal: tipoDesvioOriginalRaw
      });
    }

    return {
      skipped: true,
      discardedReason,
      noFindingSignal,
      incrementNoFindingAntes: noFindingSignal || normalizeForMatch(sanitizeHallazgo(hallazgoRawText)) === normalizeForMatch('Sin hallazgo detectado'),
      incrementConformesExplicitosReales: noFindingSignal,
      discardedByEmptyHallazgoPayload: shouldDiscardByEmptyHallazgo
        ? {
          fila: index + 1,
          fecha: normalizeCellValue(fechaRaw).trim() || '-',
          area: normalizeCellValue(areaProcesoRaw).trim() || '-',
          desvioDetectado: hallazgoRawText || '-',
          responsable: normalizeCellValue(responsableOriginalRaw).trim() || '-',
          descripcion: normalizeCellValue(descripcionRaw).trim() || '-',
          observaciones: normalizeCellValue(observacionesRaw).trim() || '-'
        }
        : null,
      discardedEmptyRowPayload: shouldDiscardAsEmptyRow
        ? {
          fila: index + 1,
          fecha: normalizeCellValue(fechaRaw).trim() || '-',
          area: normalizeCellValue(areaProcesoRaw).trim() || '-',
          hallazgo: hallazgoRawText || '-',
          responsable: normalizeCellValue(responsableOriginalRaw).trim() || '-',
          descripcion: normalizeCellValue(descripcionRaw).trim() || '-',
          observaciones: normalizeCellValue(observacionesRaw).trim() || '-',
          accion: normalizeCellValue(accionRaw).trim() || '-',
          notaTecnica: normalizeCellValue(notaTecnicaRaw).trim() || '-'
        }
        : null
    };
  }

  const rawRecord = {
    rawRowNumber: headerRowIndex + index + 1,
    rawDesvioDetectado: desvioDetectadoOriginal,
    fecha,
    areaProceso,
    actividadRealizada,
    descripcion: getRowValueByCandidates(row, rowKeyMap, [
      'Descripción',
      'Descripcion',
      'Descripción del desvío',
      'Descripcion del desvio',
      'Detalle del desvío',
      'Detalle del desvio'
    ]) || normalizeCellValue(getValue(headerIndexes.descripcion)),
    tipoActividad,
    resultado,
    desvio,
    accion,
    numeroAccion,
    notaTecnica,
    observaciones: observacionesRaw,
    accionInmediata: accionInmediataRaw,
    accionCorrectiva: accionCorrectivaRaw,
    estadoAccionRaw,
    responsableOriginal,
    iso22000Original,
    classificationOriginal,
    tipoDesvioOriginal,
    columnasOriginales: row || {},
    textoBase: actividadRealizada,
    hallazgoDetectado: sanitizeHallazgo(desvioDetectadoOriginal),
    accionDetectada
  };
  applyActionFallbacks(rawRecord, {
    row,
    rowKeyMap,
    getRowValueByCandidatesFn: getRowValueByCandidates
  });

  if (isRepeatedHeaderRow(rawRecord)) {
    return {
      skipped: true,
      discardedReason: 'encabezado_repetido',
      incrementNoFindingAntes: noFindingSignal || normalizeForMatch(sanitizeHallazgo(hallazgoRawText)) === normalizeForMatch('Sin hallazgo detectado'),
      incrementConformesExplicitosReales: noFindingSignal,
      discardedByEmptyHallazgoPayload: null,
      discardedEmptyRowPayload: null
    };
  }

  const actividadLimpia = normalizeCellValue(rawRecord.actividadRealizada).trim();
  const notaLimpia = normalizeCellValue(rawRecord.notaTecnica).trim();
  rawRecord.hallazgoDetectado = sanitizeHallazgo(rawRecord.hallazgoDetectado);
  const hallazgoSinInfo = normalizeForMatch(rawRecord.hallazgoDetectado) === normalizeForMatch('Sin hallazgo detectado');
  const notaNoAporta = !notaLimpia || notaLimpia.length <= 10 || esTextoAccion(notaLimpia);
  const casoVacio = !actividadLimpia && notaNoAporta;

  if (shouldUseAreaProcesoAsHallazgo({
    actividadRealizada: rawRecord.actividadRealizada,
    areaProceso: rawRecord.areaProceso,
    hallazgoDetectado: rawRecord.hallazgoDetectado
  })) {
    rawRecord.hallazgoDetectado = sanitizeHallazgo(rawRecord.areaProceso);
    rawRecord.areaProceso = 'Sin área/proceso original';
  }

  const textForClassification = buildClassificationText({
    areaProceso: rawRecord.areaProceso,
    actividadRealizada: rawRecord.actividadRealizada,
    hallazgoDetectado: rawRecord.hallazgoDetectado
  });
  const auditComplianceRule = classifyAuditCompliance(textForClassification);
  const explicitNegativeInRow = hasExplicitNegativeSignal(textForClassification);
  const neutralTechnicalRow = isNeutralTechnicalMention(textForClassification);
  const criticalSignalFromClassificationText = detectCriticalNegativeSignal(textForClassification);
  const criticalSignalFromHallazgo = detectCriticalNegativeSignal(rawRecord.hallazgoDetectado);
  const criticalSignal = criticalSignalFromClassificationText || criticalSignalFromHallazgo;
  const explicitNoFindingRow = isExplicitNoFindingText(textForClassification);
  const inheritedNegativeContext = contextState.negativeLeadWindow > 0 && neutralTechnicalRow && !explicitNoFindingRow;
  if (enableClassificationTrace) {
    console.log('INPUT:', textForClassification);
  }
  const explicitAreaFromExcel = normalizeBrunoArea(rawRecord.areaProceso, textForClassification);
  const detectedCompanyArea = detectCompanyAreaFromRecord({
    rawRecord,
    hallazgo: rawRecord.hallazgoDetectado,
    descripcion: rawRecord.descripcion,
    observaciones: rawRecord.observaciones,
    textForClassification
  });

  let areaResult = detectedCompanyArea
    ? { areas: [detectedCompanyArea], evidence: ['empresa/cliente detectado en el texto del desvío'] }
    : detectAreasFromDescription(textForClassification, rawRecord.areaProceso);
  let areaClasificada = areaResult.areas.join(', ');
  let areaEvidence = areaResult.evidence;
  let { resultadoClasificado, tipoDesvio, reason: outcomeReason } = classifyOutcomeFromRow({
    resultado: rawRecord.resultado,
    desvio: rawRecord.desvio,
    descripcionDetectada: textForClassification,
    tipoActividad: rawRecord.tipoActividad,
    context: {
      inheritedNegativeContext
    }
  });
  let iso22000 = classifyIso22000FromDescription({
    areaClasificada,
    descripcionDetectada: rawRecord.hallazgoDetectado,
    resultadoClasificado,
    actividadRealizada: rawRecord.actividadRealizada
  });
  if (!detectedCompanyArea && explicitAreaFromExcel) {
    areaClasificada = explicitAreaFromExcel;
    areaEvidence = ['área/sector explícito informado en Excel'];
  }

  if (hallazgoSinInfo) {
    rawRecord.hallazgoDetectado = 'Sin hallazgo detectado';
    areaClasificada = 'Área no identificada';
    areaEvidence = ['sin hallazgo explícito'];
  }

  const keepAsOperationalFinding = hasOperationalDeviationSignal(rawRecord.hallazgoDetectado);
  if (hallazgoSinInfo && casoVacio && !keepAsOperationalFinding) {
    rawRecord.hallazgoDetectado = 'Sin hallazgo detectado';
    areaClasificada = 'Área no identificada';
    resultadoClasificado = 'Revisar manualmente';
    tipoDesvio = '-';
    iso22000 = 'Revisar manualmente';
    areaEvidence = ['texto vacío'];
    outcomeReason = 'sin información suficiente';
  }

  const operationalOverride = applyOperationalOverrides({
    hallazgoDetectado: rawRecord.hallazgoDetectado,
    areaClasificada,
    resultadoClasificado,
    tipoDesvio,
    iso22000
  });
  areaClasificada = operationalOverride.areaClasificada;
  resultadoClasificado = operationalOverride.resultadoClasificado;
  tipoDesvio = operationalOverride.tipoDesvio;
  iso22000 = operationalOverride.iso22000;
  if (detectedCompanyArea) {
    areaClasificada = detectedCompanyArea;
  } else if (explicitAreaFromExcel) {
    areaClasificada = explicitAreaFromExcel;
  }

  const tipoOriginal = parseOriginalTipoDesvio(rawRecord.classificationOriginal || rawRecord.tipoDesvioOriginal || rawRecord.resultado);
  const hasOriginalClassification = normalizeCellValue(classificationOriginalRaw).trim().length > 0;
  const hasStrongNeutralEvidence = neutralTechnicalRow && !explicitNegativeInRow && !inheritedNegativeContext;
  if (!hasOriginalClassification && tipoOriginal === 'NC') {
    if (explicitNegativeInRow || inheritedNegativeContext || !hasStrongNeutralEvidence) {
      resultadoClasificado = 'No conforme';
      tipoDesvio = 'NC';
      outcomeReason = 'Resultado original del Excel aplicado (NC)';
    } else {
      resultadoClasificado = 'Conforme';
      tipoDesvio = '-';
      outcomeReason = 'texto técnico neutro; se evita override NC ambiguo del Excel';
    }
  } else if (!hasOriginalClassification && tipoOriginal === 'OBS') {
    if (!criticalSignal) {
      resultadoClasificado = 'Observación';
      tipoDesvio = 'OBS';
      outcomeReason = 'OBS por tipo original y señal leve';
    } else {
      outcomeReason = `Tipo original del Excel ignorado por señal crítica: ${criticalSignal}`;
    }
  } else if (!hasOriginalClassification && tipoOriginal === 'OM') {
    resultadoClasificado = 'Oportunidad de mejora';
    tipoDesvio = 'OM';
    outcomeReason = 'Resultado original del Excel aplicado (OM)';
  } else if (!hasOriginalClassification && tipoOriginal === 'NA') {
    if (!criticalSignal) {
      resultadoClasificado = 'Conforme';
      tipoDesvio = '-';
      outcomeReason = 'Resultado original del Excel aplicado (NA)';
    } else {
      outcomeReason = `Tipo original del Excel ignorado por señal crítica: ${criticalSignal}`;
    }
  }

  if (!hasOriginalClassification && auditComplianceRule) {
    resultadoClasificado = auditComplianceRule.classification;
    tipoDesvio = auditComplianceRule.tipoDesvio;
    outcomeReason = auditComplianceRule.reason;
  }

  if (!hasOriginalClassification && criticalSignal && !explicitNoFindingRow) {
    resultadoClasificado = 'No conforme';
    tipoDesvio = 'NC';
    outcomeReason = `NC por señal crítica: ${criticalSignal}`;
  }

  if (normalizeCellValue(rawRecord.iso22000Original).trim()) {
    iso22000 = normalizeCellValue(rawRecord.iso22000Original).trim();
    if (!outcomeReason) outcomeReason = 'ISO original del Excel aplicado';
  }
  iso22000 = resolveIsoWithContextFallback({
    iso22000,
    hallazgoDetectado: rawRecord.hallazgoDetectado,
    actividadRealizada: rawRecord.actividadRealizada,
    areaClasificada,
    resultadoClasificado
  });

  const normalizedRule = classifyNormalizedRule(textForClassification);
  if (!hasOriginalClassification && normalizedRule) {
    resultadoClasificado = normalizedRule.resultadoClasificado;
    tipoDesvio = normalizedRule.tipoDesvio;
    iso22000 = normalizedRule.iso22000;
    outcomeReason = normalizedRule.reason;
  }

  const priorityOperationalRule = classifyPriorityOperationalRule(textForClassification);
  if (!hasOriginalClassification && priorityOperationalRule && !normalizedRule) {
    resultadoClasificado = priorityOperationalRule.resultadoClasificado;
    tipoDesvio = priorityOperationalRule.tipoDesvio;
    iso22000 = priorityOperationalRule.iso22000;
    outcomeReason = priorityOperationalRule.reason;
  }

  const technicalControlRule = classifyTechnicalControlRule(textForClassification);
  if (!hasOriginalClassification && technicalControlRule && !priorityOperationalRule && !normalizedRule) {
    resultadoClasificado = technicalControlRule.resultadoClasificado;
    tipoDesvio = technicalControlRule.tipoDesvio;
    iso22000 = technicalControlRule.iso22000;
    outcomeReason = technicalControlRule.reason;
  }

  iso22000 = mergeCompositeIsoLabels({
    iso22000,
    hallazgoDetectado: rawRecord.hallazgoDetectado,
    actividadRealizada: rawRecord.actividadRealizada,
    areaClasificada
  });

  let categoriaDesvio = classifyCategoriaDesvio({
    hallazgoDetectado: rawRecord.hallazgoDetectado,
    actividadRealizada: rawRecord.actividadRealizada,
    accionInmediata: rawRecord.accionInmediata,
    accionCorrectiva: rawRecord.accionCorrectiva,
    resultadoClasificado,
    tipoDesvio,
    iso22000
  });

  const governanceAdjusted = hasOriginalClassification ? {
    resultadoClasificado,
    tipoDesvio,
    iso22000,
    categoriaDesvio
  } : applyGovernanceTypeAndCategory({
    hallazgoDetectado: rawRecord.hallazgoDetectado,
    actividadRealizada: rawRecord.actividadRealizada,
    areaClasificada,
    resultadoClasificado,
    tipoDesvio,
    iso22000,
    categoriaDesvio
  });
  resultadoClasificado = governanceAdjusted.resultadoClasificado;
  tipoDesvio = governanceAdjusted.tipoDesvio;
  iso22000 = governanceAdjusted.iso22000;
  categoriaDesvio = governanceAdjusted.categoriaDesvio || categoriaDesvio;

  const actions = buildActions({
    resultadoClasificado,
    text: textForClassification,
    hallazgoDetectado: rawRecord.hallazgoDetectado,
    accionInmediataOriginal: rawRecord.accionInmediata,
    accionCorrectivaOriginal: rawRecord.accionCorrectiva,
    categoriaDesvio,
    iso22000
  });
  rawRecord.accionInmediata = actions.accionInmediata;
  rawRecord.accionCorrectiva = actions.accionCorrectiva;
  if (enableClassificationTrace) {
    console.log('RESULTADO CLASIFICADO:', {
      row: index + 1,
      resultadoClasificado,
      tipoDesvio,
      areaClasificada,
      iso22000
    });
  }

  const finalAuditRule = classifyAuditCompliance([
    textForClassification,
    rawRecord.hallazgoDetectado,
    rawRecord.actividadRealizada
  ].join(' | '));
  if (!hasOriginalClassification && finalAuditRule && finalAuditRule.classification === 'No conforme') {
    resultadoClasificado = 'No conforme';
    tipoDesvio = 'NC';
    iso22000 = '9.2 Auditoría interna';
    outcomeReason = 'NC por auditoría con cumplimiento menor a 70%';
  }

  const preExplicacionClasificacion = buildClassificationExplanation({
    areaClasificada,
    resultadoClasificado,
    iso22000,
    areaEvidence,
    outcomeReason
  });
  const preConfianza = classifyConfidence({
    areaEvidenceCount: areaEvidence.length,
    resultadoClasificado,
    classificationText: textForClassification,
    areaClasificada
  });

  const refinadoPorIA = false;

  const areaOperativaClasificada = areaClasificada;
  let areaClasificadaFinal = detectedCompanyArea
    ? detectedCompanyArea
    : composeAreaClasificada({
      areaProcesoOriginal: rawRecord.areaProceso,
      areaOperativaDetectada: areaOperativaClasificada,
      contextText: textForClassification
    });
  const areaOriginalPreservable = hasExplicitOriginalValue(areaOriginal) ? areaOriginal : '';
  const isAuditText = containsAny(normalizeIncidentText(textForClassification), ['auditoria', 'auditoría']);
  if (isAuditText) {
    areaClasificadaFinal = 'Área no identificada';
  }
  if (areaOriginalPreservable) {
    areaClasificadaFinal = areaOriginalPreservable;
  }
  const responsable = normalizeCellValue(rawRecord.responsableOriginal).trim() || classifyResponsibleByArea(areaClasificadaFinal);

  const estadoAccion = classifyActionStatusFromRow({
    actividadRealizada: rawRecord.actividadRealizada,
    accion: rawRecord.accion,
    numeroAccion: rawRecord.numeroAccion,
    notaTecnica: rawRecord.notaTecnica,
    resultadoClasificado,
    accionDetectada: rawRecord.accionDetectada,
    accionInmediata: rawRecord.accionInmediata,
    accionCorrectiva: rawRecord.accionCorrectiva,
    fechaRegistro: rawRecord.fecha,
    estadoExplicito: rawRecord.estadoAccionRaw
  });

  const explicacionClasificacion = preExplicacionClasificacion;
  const confianza = preConfianza;
  const {
    alcanceDesvio,
    alcanceReason,
    alcanceConfidence
  } = resolveScopeMetadata({
    scopeOriginalRaw,
    row,
    rowKeyMap,
    getRowValueByCandidatesFn: getRowValueByCandidates,
    normalizeScopeFn: normalizeScope,
    classifyDeviationScopeFn: classifyDeviationScope,
    textForClassification,
    rawRecord,
    areaClasificadaFinal,
    detectedCompanyArea
  });

  const analisisTexto = buildAnalysisText(rawRecord);

  const finalRecord = validateFinalRecord(buildFinalRecordPayload({
    rawRecord,
    areaClasificadaFinal,
    resultadoClasificado,
    tipoDesvio,
    iso22000,
    categoriaDesvio,
    responsable,
    estadoAccion,
    alcanceDesvio,
    alcanceReason,
    alcanceConfidence,
    refinadoPorIA,
    explicacionClasificacion,
    confianza,
    analisisTexto,
    hasOriginalClassification,
    tipoDesvioOriginalRaw: classificationOriginalRaw,
    accionInmediataRaw,
    accionCorrectivaRaw
  }));

  applyOriginalClassificationOverride(finalRecord, {
    hasOriginalClassification,
    tipoDesvioOriginalRaw: classificationOriginalRaw,
    tipoOriginal
  });

  applyInocuidadHardPriority({
    finalRecord,
    hasOriginalClassification,
    tipoDesvioOriginalRaw: classificationOriginalRaw
  });

  finalRecord.alcanceDesvio = scopeOriginalRaw || finalRecord.alcanceDesvio;
  finalRecord.scope_original = scopeOriginalRaw || null;
  finalRecord.scope_normalized = normalizeScopeForStats(finalRecord.alcanceDesvio);
  finalRecord.immediate_action = normalizeCellValue(accionInmediataRaw).trim();
  finalRecord.corrective_action = normalizeCellValue(accionCorrectivaRaw).trim();

  if (hasExplicitOriginalValue(estadoAccionRaw)) {
    finalRecord.estadoAccion = normalizeCellValue(estadoAccionRaw).trim();
    finalRecord.estadoAcciones = normalizeCellValue(estadoAccionRaw).trim();
  }
  if (hasExplicitOriginalValue(responsableOriginalRaw)) {
    finalRecord.responsable = normalizeCellValue(responsableOriginalRaw).trim();
  }
  if (hasExplicitOriginalValue(accionInmediataRaw)) {
    finalRecord.accionInmediata = normalizeCellValue(accionInmediataRaw).trim();
    finalRecord.immediate_action = normalizeCellValue(accionInmediataRaw).trim();
  }
  if (hasExplicitOriginalValue(accionCorrectivaRaw)) {
    finalRecord.accionCorrectiva = normalizeCellValue(accionCorrectivaRaw).trim();
    finalRecord.corrective_action = normalizeCellValue(accionCorrectivaRaw).trim();
  }
  if (areaOriginalPreservable) {
    finalRecord.areaClasificada = areaOriginalPreservable;
    finalRecord.areaSector = areaOriginalPreservable;
  }
  if (hasExplicitOriginalValue(scopeOriginalRaw)) {
    const scopeOriginal = normalizeCellValue(scopeOriginalRaw).trim();
    finalRecord.alcanceDesvio = scopeOriginal;
    finalRecord.scope_original = scopeOriginal;
    finalRecord.scope_normalized = normalizeScopeForStats(scopeOriginal);
  }
  if (hasExplicitOriginalValue(iso22000OriginalRaw)) {
    const isoOriginal = normalizeCellValue(iso22000OriginalRaw).trim();
    finalRecord.iso22000 = isoOriginal;
    finalRecord.relacionIso22000 = isoOriginal;
  }
  finalRecord.traceability = {
    areaSector: {
      valor_original_excel: areaOriginalPreservable || null,
      valor_final_usado: finalRecord.areaSector || finalRecord.areaClasificada || null,
      fuente_del_valor: areaOriginalPreservable ? 'excel' : 'heuristica'
    },
    clasificacion: {
      valor_original_excel: hasOriginalClassification ? normalizeCellValue(classificationOriginalRaw).trim() : null,
      valor_final_usado: finalRecord.clasificacionDesvio || finalRecord.categoriaDesvio || null,
      fuente_del_valor: hasOriginalClassification ? 'excel' : 'heuristica'
    },
    tipo: {
      valor_original_excel: hasExplicitOriginalValue(scopeOriginalRaw) ? normalizeCellValue(scopeOriginalRaw).trim() : null,
      valor_final_usado: finalRecord.scope_normalized || finalRecord.alcanceDesvio || null,
      fuente_del_valor: hasExplicitOriginalValue(scopeOriginalRaw) ? 'excel' : 'heuristica'
    },
    estado: {
      valor_original_excel: hasExplicitOriginalValue(estadoAccionRaw) ? normalizeCellValue(estadoAccionRaw).trim() : null,
      valor_final_usado: finalRecord.estadoAcciones || finalRecord.estadoAccion || null,
      fuente_del_valor: hasExplicitOriginalValue(estadoAccionRaw) ? 'excel' : 'heuristica'
    },
    relacionIso22000: {
      valor_original_excel: hasExplicitOriginalValue(iso22000OriginalRaw) ? normalizeCellValue(iso22000OriginalRaw).trim() : null,
      valor_final_usado: finalRecord.relacionIso22000 || finalRecord.iso22000 || null,
      fuente_del_valor: hasExplicitOriginalValue(iso22000OriginalRaw) ? 'excel' : 'heuristica'
    },
    accionInmediata: {
      valor_original_excel: hasExplicitOriginalValue(accionInmediataRaw) ? normalizeCellValue(accionInmediataRaw).trim() : null,
      valor_final_usado: finalRecord.immediate_action || finalRecord.accionInmediata || null,
      fuente_del_valor: hasExplicitOriginalValue(accionInmediataRaw) ? 'excel' : 'heuristica'
    },
    accionCorrectiva: {
      valor_original_excel: hasExplicitOriginalValue(accionCorrectivaRaw) ? normalizeCellValue(accionCorrectivaRaw).trim() : null,
      valor_final_usado: finalRecord.corrective_action || finalRecord.accionCorrectiva || null,
      fuente_del_valor: hasExplicitOriginalValue(accionCorrectivaRaw) ? 'excel' : 'heuristica'
    },
    responsable: {
      valor_original_excel: hasExplicitOriginalValue(responsableOriginalRaw) ? normalizeCellValue(responsableOriginalRaw).trim() : null,
      valor_final_usado: finalRecord.responsable || null,
      fuente_del_valor: hasExplicitOriginalValue(responsableOriginalRaw) ? 'excel' : 'heuristica'
    }
  };

  // Ajuste final: la acción correctiva debe responder a la categoría final validada.
  if (!hasOriginalClassification && normalizeCellValue(finalRecord.resultadoClasificado).trim() === 'No conforme') {
    const finalActions = buildActions({
      resultadoClasificado: finalRecord.resultadoClasificado,
      text: [finalRecord.hallazgoDetectado, finalRecord.descripcion, finalRecord.observaciones, finalRecord.actividadRealizada].filter(Boolean).join(' | '),
      hallazgoDetectado: finalRecord.hallazgoDetectado,
      accionInmediataOriginal: finalRecord.accionInmediata,
      accionCorrectivaOriginal: finalRecord.accionCorrectiva,
      categoriaDesvio: finalRecord.categoriaDesvio,
      iso22000: finalRecord.iso22000
    });
    finalRecord.accionInmediata = finalActions.accionInmediata || finalRecord.accionInmediata;
    finalRecord.accionCorrectiva = finalActions.accionCorrectiva || finalRecord.accionCorrectiva;
  }

  const explicitRawNoFinding = isExplicitNoFindingRawValue(rawRecord.rawDesvioDetectado || finalRecord.rawDesvioDetectado || '');
  const isAutoConforme = isAutoGeneratedConformeRecord(finalRecord);

  const shouldOpenNegativeLead = hasRowContinuationSignal(rawRecord.hallazgoDetectado)
    && (explicitNegativeInRow || /falta\s*[;:,]?\s*$/i.test(normalizeCellValue(rawRecord.hallazgoDetectado)));
  if (explicitNoFindingRow) {
    contextState.negativeLeadWindow = 0;
    contextState.leadTopicText = '';
  } else if (shouldOpenNegativeLead) {
    contextState.negativeLeadWindow = contextState.maxLeadWindow;
    contextState.leadTopicText = normalizeIncidentText(textForClassification);
  } else if (contextState.negativeLeadWindow > 0) {
    const rowHasOwnCompleteSignal = explicitNegativeInRow || !neutralTechnicalRow;
    if (rowHasOwnCompleteSignal) {
      contextState.negativeLeadWindow = 0;
      contextState.leadTopicText = '';
    } else {
      contextState.negativeLeadWindow -= 1;
    }
  }

  return {
    skipped: false,
    incrementConformesExplicitosReales: noFindingSignal,
    incrementNoFindingAntes: noFindingSignal || normalizeForMatch(sanitizeHallazgo(hallazgoRawText)) === normalizeForMatch('Sin hallazgo detectado'),
    discardedByEmptyHallazgoPayload: null,
    discardedEmptyRowPayload: null,
    finalRecord,
    rawRecord,
    dateDebug: {
      rowNumber: headerRowIndex + index + 1,
      rawDateValue: fechaRaw,
      rawDateType: inferRawDateType(fechaRaw),
      parsedDate: finalRecord?.fecha || '',
      contextYearUsed: fillDownState.contextYear,
      parserUsed: 'parseFechaValue+fillDown',
      usedCurrentYearFallback: false
    },
    isAutoConforme,
    explicitRawNoFinding
  };
}

export {
  processRow
};
