import {
  normalizeCellValue,
  normalizeForMatch,
  containsAny,
  getRowValueByCandidates,
  normalizeIncidentText
} from '../../analyzeExcel/normalizers.js';
import {
  classifyAuditCompliance,
  hasExplicitNegativeSignal,
  detectCriticalNegativeSignal,
  isNeutralTechnicalMention,
  classifyTechnicalControlRule,
  classifyPriorityOperationalRule,
  hasRowContinuationSignal,
  isExplicitNoFindingText,
  isExplicitNoFindingRawValue,
  isAutoGeneratedConformeRecord,
  classifyNormalizedRule,
  classifyOutcomeFromRow,
  parseOriginalTipoDesvio
} from './classifiers/outcomeClassifier.js';
import {
  classifyIso22000FromDescription,
  mergeCompositeIsoLabels,
  resolveIsoWithContextFallback
} from './classifiers/isoClassifier.js';
import {
  classifyCategoriaDesvio,
  applyGovernanceTypeAndCategory
} from './classifiers/categoryClassifier.js';
import { classifyDeviationScope, normalizeScope } from './classifiers/scopeClassifier.js';
import {
  hasOperationalDeviationSignal,
  shouldUseAreaProcesoAsHallazgo,
  applyOperationalOverrides,
  detectAreasFromDescription,
  composeAreaClasificada,
  normalizeBrunoArea
} from './classifiers/areaClassifier.js';
import {
  esTextoAccion,
  buildActions,
  classifyResponsibleByArea,
  classifyActionStatusFromRow
} from './actions.js';
import { validateFinalRecord } from './validation.js';
import { detectCompanyAreaFromRecord } from './companyDetector.js';
import {
  inferRawDateType,
  sanitizeHallazgo,
  isRepeatedHeaderRow,
  buildClassificationText,
  buildClassificationExplanation,
  classifyConfidence,
  buildAnalysisText,
  applyActionFallbacks,
  buildFinalRecordPayload,
  resolveScopeMetadata,
} from './recordProcessor.utils.js';
import { extractInitialRecordFields } from './recordProcessor/fieldExtraction.js';
import { buildDiscardedRowResult } from './recordProcessor/discardResult.js';
import { applyFinalRecordOverrides } from './recordProcessor/finalRecordOverrides.js';
import { updateNegativeLeadContext } from './recordProcessor/contextContinuation.js';
import { hasExplicitOriginalValue } from './recordProcessor/helpers.js';

function processRow({
  index,
  rowValues,
  headerRowIndex,
  headerValues,
  headerIndexes,
  fillDownState,
  contextState,
  enableClassificationTrace,
  enableFillDownTrace
}) {
  const {
    row,
    rowKeyMap,
    getValue,
    accionDetectada,
    areaProcesoRaw,
    accionRaw,
    numeroAccionRaw,
    notaTecnicaRaw,
    fechaRaw,
    responsableOriginalRaw,
    iso22000OriginalRaw,
    classificationOriginalRaw,
    tipoDesvioOriginalRaw,
    scopeOriginalRaw,
    desvioDetectadoOriginal,
    areaOriginal,
    descripcionRaw,
    observacionesRaw,
    accionInmediataRaw,
    accionCorrectivaRaw,
    estadoAccionRaw,
    hallazgoRawText,
    noFindingSignal,
    becameNoFindingAfterSanitize,
    shouldDiscardByEmptyHallazgo,
    shouldDiscardAsEmptyRow,
    fecha,
    areaProceso,
    actividadRealizada,
    tipoActividad,
    resultado,
    desvio,
    accion,
    numeroAccion,
    notaTecnica,
    responsableOriginal,
    iso22000Original,
    classificationOriginal,
    tipoDesvioOriginal,
    hasRealRowSignal,
    invalidDetectedFinding
  } = extractInitialRecordFields({
    rowValues,
    headerValues,
    headerIndexes,
    fillDownState
  });

  if (!hasRealRowSignal || invalidDetectedFinding || shouldDiscardAsEmptyRow || shouldDiscardByEmptyHallazgo) {
    return buildDiscardedRowResult({
      index,
      enableFillDownTrace,
      shouldDiscardByEmptyHallazgo,
      becameNoFindingAfterSanitize,
      shouldDiscardAsEmptyRow,
      hasRealRowSignal,
      noFindingSignal,
      hallazgoRawText,
      desvioDetectadoOriginal,
      areaOriginal,
      tipoDesvioOriginalRaw,
      fechaRaw,
      areaProcesoRaw,
      responsableOriginalRaw,
      descripcionRaw,
      observacionesRaw,
      accionRaw,
      notaTecnicaRaw
    });
  }

  const rawRecord = {
    rawRowNumber: headerRowIndex + index + 1,
    rawDesvioDetectado: desvioDetectadoOriginal,
    fecha,
    areaProceso,
    actividadRealizada,
    descripcion: getRowValueByCandidates(row, rowKeyMap, [
      'Descripción',
      'Descripcion',
      'Descripción del desvío',
      'Descripcion del desvio',
      'Detalle del desvío',
      'Detalle del desvio'
    ]) || normalizeCellValue(getValue(headerIndexes.descripcion)),
    tipoActividad,
    resultado,
    desvio,
    accion,
    numeroAccion,
    notaTecnica,
    observaciones: observacionesRaw,
    accionInmediata: accionInmediataRaw,
    accionCorrectiva: accionCorrectivaRaw,
    estadoAccionRaw,
    responsableOriginal,
    iso22000Original,
    classificationOriginal,
    tipoDesvioOriginal,
    columnasOriginales: row || {},
    textoBase: actividadRealizada,
    hallazgoDetectado: sanitizeHallazgo(desvioDetectadoOriginal),
    accionDetectada
  };
  applyActionFallbacks(rawRecord, {
    row,
    rowKeyMap,
    getRowValueByCandidatesFn: getRowValueByCandidates
  });

  if (isRepeatedHeaderRow(rawRecord)) {
    return {
      skipped: true,
      discardedReason: 'encabezado_repetido',
      incrementNoFindingAntes: noFindingSignal || normalizeForMatch(sanitizeHallazgo(hallazgoRawText)) === normalizeForMatch('Sin hallazgo detectado'),
      incrementConformesExplicitosReales: noFindingSignal,
      discardedByEmptyHallazgoPayload: null,
      discardedEmptyRowPayload: null
    };
  }

  const actividadLimpia = normalizeCellValue(rawRecord.actividadRealizada).trim();
  const notaLimpia = normalizeCellValue(rawRecord.notaTecnica).trim();
  rawRecord.hallazgoDetectado = sanitizeHallazgo(rawRecord.hallazgoDetectado);
  const hallazgoSinInfo = normalizeForMatch(rawRecord.hallazgoDetectado) === normalizeForMatch('Sin hallazgo detectado');
  const notaNoAporta = !notaLimpia || notaLimpia.length <= 10 || esTextoAccion(notaLimpia);
  const casoVacio = !actividadLimpia && notaNoAporta;

  if (shouldUseAreaProcesoAsHallazgo({
    actividadRealizada: rawRecord.actividadRealizada,
    areaProceso: rawRecord.areaProceso,
    hallazgoDetectado: rawRecord.hallazgoDetectado
  })) {
    rawRecord.hallazgoDetectado = sanitizeHallazgo(rawRecord.areaProceso);
    rawRecord.areaProceso = 'Sin área/proceso original';
  }

  const textForClassification = buildClassificationText({
    areaProceso: rawRecord.areaProceso,
    actividadRealizada: rawRecord.actividadRealizada,
    hallazgoDetectado: rawRecord.hallazgoDetectado
  });
  const auditComplianceRule = classifyAuditCompliance(textForClassification);
  const explicitNegativeInRow = hasExplicitNegativeSignal(textForClassification);
  const neutralTechnicalRow = isNeutralTechnicalMention(textForClassification);
  const criticalSignalFromClassificationText = detectCriticalNegativeSignal(textForClassification);
  const criticalSignalFromHallazgo = detectCriticalNegativeSignal(rawRecord.hallazgoDetectado);
  const criticalSignal = criticalSignalFromClassificationText || criticalSignalFromHallazgo;
  const explicitNoFindingRow = isExplicitNoFindingText(textForClassification);
  const inheritedNegativeContext = contextState.negativeLeadWindow > 0 && neutralTechnicalRow && !explicitNoFindingRow;
  if (enableClassificationTrace) {
    console.log('INPUT:', textForClassification);
  }
  const explicitAreaFromExcel = normalizeBrunoArea(rawRecord.areaProceso, textForClassification);
  const detectedCompanyArea = detectCompanyAreaFromRecord({
    rawRecord,
    hallazgo: rawRecord.hallazgoDetectado,
    descripcion: rawRecord.descripcion,
    observaciones: rawRecord.observaciones,
    textForClassification
  });

  let areaResult = detectedCompanyArea
    ? { areas: [detectedCompanyArea], evidence: ['empresa/cliente detectado en el texto del desvío'] }
    : detectAreasFromDescription(textForClassification, rawRecord.areaProceso);
  let areaClasificada = areaResult.areas.join(', ');
  let areaEvidence = areaResult.evidence;
  let { resultadoClasificado, tipoDesvio, reason: outcomeReason } = classifyOutcomeFromRow({
    resultado: rawRecord.resultado,
    desvio: rawRecord.desvio,
    descripcionDetectada: textForClassification,
    tipoActividad: rawRecord.tipoActividad,
    context: {
      inheritedNegativeContext
    }
  });
  let iso22000 = classifyIso22000FromDescription({
    areaClasificada,
    descripcionDetectada: rawRecord.hallazgoDetectado,
    resultadoClasificado,
    actividadRealizada: rawRecord.actividadRealizada
  });
  if (!detectedCompanyArea && explicitAreaFromExcel) {
    areaClasificada = explicitAreaFromExcel;
    areaEvidence = ['área/sector explícito informado en Excel'];
  }

  if (hallazgoSinInfo) {
    rawRecord.hallazgoDetectado = 'Sin hallazgo detectado';
    areaClasificada = 'Área no identificada';
    areaEvidence = ['sin hallazgo explícito'];
  }

  const keepAsOperationalFinding = hasOperationalDeviationSignal(rawRecord.hallazgoDetectado);
  if (hallazgoSinInfo && casoVacio && !keepAsOperationalFinding) {
    rawRecord.hallazgoDetectado = 'Sin hallazgo detectado';
    areaClasificada = 'Área no identificada';
    resultadoClasificado = 'Revisar manualmente';
    tipoDesvio = '-';
    iso22000 = 'Revisar manualmente';
    areaEvidence = ['texto vacío'];
    outcomeReason = 'sin información suficiente';
  }

  const operationalOverride = applyOperationalOverrides({
    hallazgoDetectado: rawRecord.hallazgoDetectado,
    areaClasificada,
    resultadoClasificado,
    tipoDesvio,
    iso22000
  });
  areaClasificada = operationalOverride.areaClasificada;
  resultadoClasificado = operationalOverride.resultadoClasificado;
  tipoDesvio = operationalOverride.tipoDesvio;
  iso22000 = operationalOverride.iso22000;
  if (detectedCompanyArea) {
    areaClasificada = detectedCompanyArea;
  } else if (explicitAreaFromExcel) {
    areaClasificada = explicitAreaFromExcel;
  }

  const tipoOriginal = parseOriginalTipoDesvio(rawRecord.classificationOriginal || rawRecord.tipoDesvioOriginal || rawRecord.resultado);
  const hasOriginalClassification = hasExplicitOriginalValue(classificationOriginalRaw);
  const hasStrongNeutralEvidence = neutralTechnicalRow && !explicitNegativeInRow && !inheritedNegativeContext;
  if (!hasOriginalClassification && tipoOriginal === 'NC') {
    if (explicitNegativeInRow || inheritedNegativeContext || !hasStrongNeutralEvidence) {
      resultadoClasificado = 'No conforme';
      tipoDesvio = 'NC';
      outcomeReason = 'Resultado original del Excel aplicado (NC)';
    } else {
      resultadoClasificado = 'Conforme';
      tipoDesvio = '-';
      outcomeReason = 'texto técnico neutro; se evita override NC ambiguo del Excel';
    }
  } else if (!hasOriginalClassification && tipoOriginal === 'OBS') {
    if (!criticalSignal) {
      resultadoClasificado = 'Observación';
      tipoDesvio = 'OBS';
      outcomeReason = 'OBS por tipo original y señal leve';
    } else {
      outcomeReason = `Tipo original del Excel ignorado por señal crítica: ${criticalSignal}`;
    }
  } else if (!hasOriginalClassification && tipoOriginal === 'OM') {
    resultadoClasificado = 'Oportunidad de mejora';
    tipoDesvio = 'OM';
    outcomeReason = 'Resultado original del Excel aplicado (OM)';
  } else if (!hasOriginalClassification && tipoOriginal === 'NA') {
    if (!criticalSignal) {
      resultadoClasificado = 'Conforme';
      tipoDesvio = '-';
      outcomeReason = 'Resultado original del Excel aplicado (NA)';
    } else {
      outcomeReason = `Tipo original del Excel ignorado por señal crítica: ${criticalSignal}`;
    }
  }

  if (!hasOriginalClassification && auditComplianceRule) {
    resultadoClasificado = auditComplianceRule.classification;
    tipoDesvio = auditComplianceRule.tipoDesvio;
    outcomeReason = auditComplianceRule.reason;
  }

  if (!hasOriginalClassification && criticalSignal && !explicitNoFindingRow) {
    resultadoClasificado = 'No conforme';
    tipoDesvio = 'NC';
    outcomeReason = `NC por señal crítica: ${criticalSignal}`;
  }

  if (normalizeCellValue(rawRecord.iso22000Original).trim()) {
    iso22000 = normalizeCellValue(rawRecord.iso22000Original).trim();
    if (!outcomeReason) outcomeReason = 'ISO original del Excel aplicado';
  }
  iso22000 = resolveIsoWithContextFallback({
    iso22000,
    hallazgoDetectado: rawRecord.hallazgoDetectado,
    actividadRealizada: rawRecord.actividadRealizada,
    areaClasificada,
    resultadoClasificado
  });

  const normalizedRule = classifyNormalizedRule(textForClassification);
  if (!hasOriginalClassification && normalizedRule) {
    resultadoClasificado = normalizedRule.resultadoClasificado;
    tipoDesvio = normalizedRule.tipoDesvio;
    iso22000 = normalizedRule.iso22000;
    outcomeReason = normalizedRule.reason;
  }

  const priorityOperationalRule = classifyPriorityOperationalRule(textForClassification);
  if (!hasOriginalClassification && priorityOperationalRule && !normalizedRule) {
    resultadoClasificado = priorityOperationalRule.resultadoClasificado;
    tipoDesvio = priorityOperationalRule.tipoDesvio;
    iso22000 = priorityOperationalRule.iso22000;
    outcomeReason = priorityOperationalRule.reason;
  }

  const technicalControlRule = classifyTechnicalControlRule(textForClassification);
  if (!hasOriginalClassification && technicalControlRule && !priorityOperationalRule && !normalizedRule) {
    resultadoClasificado = technicalControlRule.resultadoClasificado;
    tipoDesvio = technicalControlRule.tipoDesvio;
    iso22000 = technicalControlRule.iso22000;
    outcomeReason = technicalControlRule.reason;
  }

  iso22000 = mergeCompositeIsoLabels({
    iso22000,
    hallazgoDetectado: rawRecord.hallazgoDetectado,
    actividadRealizada: rawRecord.actividadRealizada,
    areaClasificada
  });

  let categoriaDesvio = classifyCategoriaDesvio({
    hallazgoDetectado: rawRecord.hallazgoDetectado,
    actividadRealizada: rawRecord.actividadRealizada,
    accionInmediata: rawRecord.accionInmediata,
    accionCorrectiva: rawRecord.accionCorrectiva,
    resultadoClasificado,
    tipoDesvio,
    iso22000
  });

  const governanceAdjusted = hasOriginalClassification ? {
    resultadoClasificado,
    tipoDesvio,
    iso22000,
    categoriaDesvio
  } : applyGovernanceTypeAndCategory({
    hallazgoDetectado: rawRecord.hallazgoDetectado,
    actividadRealizada: rawRecord.actividadRealizada,
    areaClasificada,
    resultadoClasificado,
    tipoDesvio,
    iso22000,
    categoriaDesvio
  });
  resultadoClasificado = governanceAdjusted.resultadoClasificado;
  tipoDesvio = governanceAdjusted.tipoDesvio;
  iso22000 = governanceAdjusted.iso22000;
  categoriaDesvio = governanceAdjusted.categoriaDesvio || categoriaDesvio;

  const actions = buildActions({
    resultadoClasificado,
    text: textForClassification,
    hallazgoDetectado: rawRecord.hallazgoDetectado,
    accionInmediataOriginal: rawRecord.accionInmediata,
    accionCorrectivaOriginal: rawRecord.accionCorrectiva,
    categoriaDesvio,
    iso22000
  });
  rawRecord.accionInmediata = actions.accionInmediata;
  rawRecord.accionCorrectiva = actions.accionCorrectiva;
  if (enableClassificationTrace) {
    console.log('RESULTADO CLASIFICADO:', {
      row: index + 1,
      resultadoClasificado,
      tipoDesvio,
      areaClasificada,
      iso22000
    });
  }

  const finalAuditRule = classifyAuditCompliance([
    textForClassification,
    rawRecord.hallazgoDetectado,
    rawRecord.actividadRealizada
  ].join(' | '));
  if (!hasOriginalClassification && finalAuditRule && finalAuditRule.classification === 'No conforme') {
    resultadoClasificado = 'No conforme';
    tipoDesvio = 'NC';
    iso22000 = '9.2 Auditoría interna';
    outcomeReason = 'NC por auditoría con cumplimiento menor a 70%';
  }

  const preExplicacionClasificacion = buildClassificationExplanation({
    areaClasificada,
    resultadoClasificado,
    iso22000,
    areaEvidence,
    outcomeReason
  });
  const preConfianza = classifyConfidence({
    areaEvidenceCount: areaEvidence.length,
    resultadoClasificado,
    classificationText: textForClassification,
    areaClasificada
  });

  const refinadoPorIA = false;

  const areaOperativaClasificada = areaClasificada;
  let areaClasificadaFinal = detectedCompanyArea
    ? detectedCompanyArea
    : composeAreaClasificada({
      areaProcesoOriginal: rawRecord.areaProceso,
      areaOperativaDetectada: areaOperativaClasificada,
      contextText: textForClassification
    });
  const areaOriginalPreservable = hasExplicitOriginalValue(areaOriginal) ? areaOriginal : '';
  const isAuditText = containsAny(normalizeIncidentText(textForClassification), ['auditoria', 'auditoría']);
  if (isAuditText) {
    areaClasificadaFinal = 'Área no identificada';
  }
  if (areaOriginalPreservable) {
    areaClasificadaFinal = areaOriginalPreservable;
  }
  const responsable = normalizeCellValue(rawRecord.responsableOriginal).trim() || classifyResponsibleByArea(areaClasificadaFinal);

  const estadoAccion = classifyActionStatusFromRow({
    actividadRealizada: rawRecord.actividadRealizada,
    accion: rawRecord.accion,
    numeroAccion: rawRecord.numeroAccion,
    notaTecnica: rawRecord.notaTecnica,
    resultadoClasificado,
    accionDetectada: rawRecord.accionDetectada,
    accionInmediata: rawRecord.accionInmediata,
    accionCorrectiva: rawRecord.accionCorrectiva,
    fechaRegistro: rawRecord.fecha,
    estadoExplicito: rawRecord.estadoAccionRaw
  });

  const explicacionClasificacion = preExplicacionClasificacion;
  const confianza = preConfianza;
  const {
    alcanceDesvio,
    alcanceReason,
    alcanceConfidence
  } = resolveScopeMetadata({
    scopeOriginalRaw,
    row,
    rowKeyMap,
    getRowValueByCandidatesFn: getRowValueByCandidates,
    normalizeScopeFn: normalizeScope,
    classifyDeviationScopeFn: classifyDeviationScope,
    textForClassification,
    rawRecord,
    areaClasificadaFinal,
    detectedCompanyArea
  });

  const analisisTexto = buildAnalysisText(rawRecord);

  const finalRecord = validateFinalRecord(buildFinalRecordPayload({
    rawRecord,
    areaClasificadaFinal,
    resultadoClasificado,
    tipoDesvio,
    iso22000,
    categoriaDesvio,
    responsable,
    estadoAccion,
    alcanceDesvio,
    alcanceReason,
    alcanceConfidence,
    refinadoPorIA,
    explicacionClasificacion,
    confianza,
    analisisTexto,
    hasOriginalClassification,
    tipoDesvioOriginalRaw: classificationOriginalRaw,
    accionInmediataRaw,
    accionCorrectivaRaw
  }));

  applyFinalRecordOverrides({
    finalRecord,
    hasOriginalClassification,
    classificationOriginalRaw,
    tipoOriginal,
    scopeOriginalRaw,
    accionInmediataRaw,
    accionCorrectivaRaw,
    estadoAccionRaw,
    responsableOriginalRaw,
    areaOriginalPreservable,
    iso22000OriginalRaw
  });

  const explicitRawNoFinding = isExplicitNoFindingRawValue(rawRecord.rawDesvioDetectado || finalRecord.rawDesvioDetectado || '');
  const isAutoConforme = isAutoGeneratedConformeRecord(finalRecord);

  updateNegativeLeadContext({
    contextState,
    rawRecord,
    textForClassification,
    explicitNoFindingRow,
    explicitNegativeInRow,
    neutralTechnicalRow,
    hasRowContinuationSignalFn: hasRowContinuationSignal
  });

  return {
    skipped: false,
    incrementConformesExplicitosReales: noFindingSignal,
    incrementNoFindingAntes: noFindingSignal || normalizeForMatch(sanitizeHallazgo(hallazgoRawText)) === normalizeForMatch('Sin hallazgo detectado'),
    discardedByEmptyHallazgoPayload: null,
    discardedEmptyRowPayload: null,
    finalRecord,
    rawRecord,
    dateDebug: {
      rowNumber: headerRowIndex + index + 1,
      rawDateValue: fechaRaw,
      rawDateType: inferRawDateType(fechaRaw),
      parsedDate: finalRecord?.fecha || '',
      contextYearUsed: fillDownState.contextYear,
      parserUsed: 'parseFechaValue+fillDown',
      usedCurrentYearFallback: false
    },
    isAutoConforme,
    explicitRawNoFinding
  };
}

export {
  processRow
};
