import { normalizeCellValue, normalizeForMatch } from '../../analyzeExcel/normalizers.js';
import { sanitizeOperationalAreaList } from './classifiers/areaClassifier.js';
import { classifyDeviationCasesFromRecords } from '../../caseClassifier.js';

function stripLegacyResultadoFields(record = {}) {
  const sanitized = { ...record };
  delete sanitized.resultado;
  return sanitized;
}

function createSummary() {
  return {
    totalRecords: 0,
    totalCases: 0,
    totalDesvios: 0,
    totalConformes: 0,
    totalInocuidad: 0,
    totalCalidad: 0,
    totalLogistica: 0,
    totalLegal: 0,
    totalRevisionManual: 0,
    totalNC: 0,
    totalOBS: 0,
    totalOM: 0,
    byArea: {},
    byTipo: {},
    byIso22000: {},
    byCategoria: {},
    noFindingAudit: {
      totalNoFindingAntes: 0,
      conformesReales: 0,
      filasVaciasDescartadas: 0,
      ejemplosDescartadas: [],
      ejemplosConformesReales: []
    },
    excelAudit: {
      totalFilasLeidas: 0,
      totalRegistrosCreados: 0,
      filasDescartadasDesvioVacio: 0,
      conformesExplicitosReales: 0,
      totalConformesAutoGenerados: 0,
      ejemplosFilasDescartadas: [],
      ejemplosRegistrosCreados: [],
      ejemplosConformesAutoGenerados: []
    },
    actions: {
      abiertas: 0,
      cerradas: 0,
      enProceso: 0,
      sinAccion: 0
    },
    timestamp: new Date().toISOString()
  };
}

function setTotalRows(summary, totalRows) {
  summary.excelAudit.totalFilasLeidas = totalRows;
}

function incrementConformesExplicitosReales(summary) {
  summary.excelAudit.conformesExplicitosReales += 1;
}

function incrementTotalNoFindingAntes(summary) {
  summary.noFindingAudit.totalNoFindingAntes += 1;
}

function registerDiscardedByEmptyHallazgo(summary, payload = {}) {
  summary.excelAudit.filasDescartadasDesvioVacio += 1;
  if (summary.excelAudit.ejemplosFilasDescartadas.length < 5) {
    summary.excelAudit.ejemplosFilasDescartadas.push(payload);
  }
}

function registerDiscardedEmptyRow(summary, payload = {}) {
  summary.noFindingAudit.filasVaciasDescartadas += 1;
  if (summary.noFindingAudit.ejemplosDescartadas.length < 5) {
    summary.noFindingAudit.ejemplosDescartadas.push(payload);
  }
}

function registerAutoGeneratedConforme(summary, finalRecord = {}, rawRecord = {}) {
  summary.excelAudit.totalConformesAutoGenerados += 1;
  if (summary.excelAudit.ejemplosConformesAutoGenerados.length < 5) {
    summary.excelAudit.ejemplosConformesAutoGenerados.push({
      rawRowNumber: finalRecord.rawRowNumber ?? rawRecord.rawRowNumber ?? '-',
      rawDesvioDetectado: normalizeCellValue(finalRecord.rawDesvioDetectado || rawRecord.rawDesvioDetectado || '').trim() || '-',
      hallazgo: normalizeCellValue(finalRecord.hallazgoDetectado).trim() || '-',
      area: normalizeCellValue(finalRecord.areaClasificada).trim() || '-',
      responsable: normalizeCellValue(finalRecord.responsable).trim() || '-',
      descripcion: normalizeCellValue(finalRecord.descripcion).trim() || '-',
      observaciones: normalizeCellValue(finalRecord.observaciones).trim() || '-',
      notaTecnica: normalizeCellValue(finalRecord.notaTecnica).trim() || '-'
    });
  }
}

function registerFinalRecordInSummary(summary, finalRecord = {}) {
  const finalResultado = normalizeCellValue(finalRecord.resultadoClasificado).trim();
  const finalTipo = normalizeCellValue(finalRecord.tipoDesvio).trim();
  const finalIso = normalizeCellValue(finalRecord.iso22000).trim() || 'Revisar manualmente';
  const finalCategoria = normalizeCellValue(finalRecord.categoriaDesvio).trim() || 'Revisar manualmente';
  const finalEstadoAccion = normalizeCellValue(finalRecord.estadoAccion).trim();
  const isConforme = finalResultado === 'Conforme';
  const isRevisionManual = finalCategoria === 'Revisar manualmente';
  const isDesvio = ['Desvío de Inocuidad', 'Desvío de Calidad', 'Desvío de Logística', 'Desvío Legal'].includes(finalCategoria);

  if (
    normalizeForMatch(normalizeCellValue(finalRecord.hallazgoDetectado)) === normalizeForMatch('Sin hallazgo detectado')
    && finalResultado === 'Conforme'
  ) {
    summary.noFindingAudit.conformesReales += 1;
    if (summary.noFindingAudit.ejemplosConformesReales.length < 5) {
      summary.noFindingAudit.ejemplosConformesReales.push({
        fecha: normalizeCellValue(finalRecord.fecha).trim() || '-',
        area: normalizeCellValue(finalRecord.areaClasificada).trim() || '-',
        hallazgo: normalizeCellValue(finalRecord.hallazgoDetectado).trim() || '-',
        responsable: normalizeCellValue(finalRecord.responsable).trim() || '-',
        descripcion: normalizeCellValue(finalRecord.descripcion).trim() || '-',
        observaciones: normalizeCellValue(finalRecord.observaciones).trim() || '-',
        accion: normalizeCellValue(finalRecord.accion).trim() || '-',
        notaTecnica: normalizeCellValue(finalRecord.notaTecnica).trim() || '-'
      });
    }
  }

  summary.totalRecords += 1;
  summary.excelAudit.totalRegistrosCreados += 1;
  if (summary.excelAudit.ejemplosRegistrosCreados.length < 5) {
    summary.excelAudit.ejemplosRegistrosCreados.push({
      fecha: normalizeCellValue(finalRecord.fecha).trim() || '-',
      area: normalizeCellValue(finalRecord.areaClasificada).trim() || '-',
      hallazgo: normalizeCellValue(finalRecord.hallazgoDetectado).trim() || '-',
      resultado: finalResultado || '-',
      categoria: finalCategoria || '-'
    });
  }

  if (isConforme) summary.totalConformes += 1;
  if (isRevisionManual) summary.totalRevisionManual += 1;
  summary.byCategoria[finalCategoria] = (summary.byCategoria[finalCategoria] || 0) + 1;
  if (finalCategoria === 'Desvío de Inocuidad') summary.totalInocuidad += 1;
  if (finalCategoria === 'Desvío de Calidad') summary.totalCalidad += 1;
  if (finalCategoria === 'Desvío de Logística') summary.totalLogistica += 1;
  if (finalCategoria === 'Desvío Legal') summary.totalLegal += 1;

  if (isDesvio) {
    summary.totalDesvios += 1;
    const areasForSummary = normalizeCellValue(finalRecord.areaClasificada)
      .split(',')
      .flatMap((value) => value.split('/'))
      .map((value) => value.trim())
      .filter(Boolean);
    const uniqueAreasForSummary = [...new Set(sanitizeOperationalAreaList(areasForSummary))];
    uniqueAreasForSummary.forEach((areaItem) => {
      summary.byArea[areaItem] = (summary.byArea[areaItem] || 0) + 1;
    });
    summary.byIso22000[finalIso] = (summary.byIso22000[finalIso] || 0) + 1;
    summary.byTipo[finalTipo] = (summary.byTipo[finalTipo] || 0) + 1;
  }

  if (finalTipo === 'NC') summary.totalNC += 1;
  if (finalTipo === 'OBS') summary.totalOBS += 1;
  if (finalTipo === 'OM') summary.totalOM += 1;

  if (finalEstadoAccion === 'abierta') summary.actions.abiertas += 1;
  if (finalEstadoAccion === 'cerrada') summary.actions.cerradas += 1;
  if (finalEstadoAccion === 'en_proceso') summary.actions.enProceso += 1;
  if (finalEstadoAccion === 'sin_accion') summary.actions.sinAccion += 1;
}

function buildSuccessPayload(results = [], summary = {}) {
  const cases = classifyDeviationCasesFromRecords(results);
  summary.totalCases = cases.length;

  const responseRecords = results.map((record) => stripLegacyResultadoFields(record));

  return {
    success: true,
    records: responseRecords,
    cases,
    summary
  };
}

export {
  createSummary,
  setTotalRows,
  incrementConformesExplicitosReales,
  incrementTotalNoFindingAntes,
  registerDiscardedByEmptyHallazgo,
  registerDiscardedEmptyRow,
  registerAutoGeneratedConforme,
  registerFinalRecordInSummary,
  buildSuccessPayload
};
